export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_LATEST_ITEMS = 'RECEIVE_LATEST_ITEMS';
export const RECEIVE_ITEM_DETAIL = 'RECEIVE_ITEM_DETAIL';